title: Uzair Akbar
author: Uzair Akbar
subtitle: A place to dump my study notes.

google_analytics: UA-227265779-1

url:
baseurl:

footer_url: "https://www.uzairakbar.com"
footer_text: "Uzair Akbar"

profile-picture: assets/profile.png
favicon_location: assets/icons/favicon/favicon120.png
social_icons: assets/icons/socials

permalink: /:categories/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "cv"
   link: "/uzair_cv.pdf"
 - name: "notes"
   link: "/notes"

markdown: kramdown
kramdown:
  math_engine: katex
